all: cvmod.o dat.o fcons.o fdown.o fdup.o ffileread.o ffilewrite.o fgetline.o \
  file_raise.o fileclose.o fileluopen.o filemopen.o fileopen.o filepos.o \
  fileread.o filereopen.o fileseek.o filesize.o filestat.o filewrite.o \
  flag.o flush.o fpipe.o niread.o niwrite.o nixread.o nixwrite.o openfd.o \
  peekc.o

clean:
	rm -f *.o

cvmod.o: cvmod.c
	${CC} ${FLAGS} -c -I ../../include/ -o cvmod.o cvmod.c

dat.o: dat.c
	${CC} ${FLAGS} -c -I ../../include/ -o dat.o dat.c

fcons.o: fcons.c
	${CC} ${FLAGS} -c -I ../../include/ -o fcons.o fcons.c

fdown.o: fdown.c
	${CC} ${FLAGS} -c -I ../../include/ -o fdown.o fdown.c

fdup.o: fdup.c
	${CC} ${FLAGS} -c -I ../../include/ -o fdup.o fdup.c

ffileread.o: ffileread.c
	${CC} ${FLAGS} -c -I ../../include/ -o ffileread.o ffileread.c

ffilewrite.o: ffilewrite.c
	${CC} ${FLAGS} -c -I ../../include/ -o ffilewrite.o ffilewrite.c

fgetline.o: fgetline.c
	${CC} ${FLAGS} -c -I ../../include/ -o fgetline.o fgetline.c

file_raise.o: file_raise.c
	${CC} ${FLAGS} -c -I ../../include/ -o file_raise.o file_raise.c

fileclose.o: fileclose.c
	${CC} ${FLAGS} -c -I ../../include/ -o fileclose.o fileclose.c

fileluopen.o: fileluopen.c
	${CC} ${FLAGS} -c -I ../../include/ -o fileluopen.o fileluopen.c

filemopen.o: filemopen.c
	${CC} ${FLAGS} -c -I ../../include/ -o filemopen.o filemopen.c

fileopen.o: fileopen.c
	${CC} ${FLAGS} -c -I ../../include/ -o fileopen.o fileopen.c

filepos.o: filepos.c
	${CC} ${FLAGS} -c -I ../../include/ -o filepos.o filepos.c

fileread.o: fileread.c
	${CC} ${FLAGS} -c -I ../../include/ -o fileread.o fileread.c

filereopen.o: filereopen.c
	${CC} ${FLAGS} -c -I ../../include/ -o filereopen.o filereopen.c

fileseek.o: fileseek.c
	${CC} ${FLAGS} -c -I ../../include/ -o fileseek.o fileseek.c

filesize.o: filesize.c
	${CC} ${FLAGS} -c -I ../../include/ -o filesize.o filesize.c

filestat.o: filestat.c
	${CC} ${FLAGS} -c -I ../../include/ -o filestat.o filestat.c

filewrite.o: filewrite.c
	${CC} ${FLAGS} -c -I ../../include/ -o filewrite.o filewrite.c

flag.o: flag.c
	${CC} ${FLAGS} -c -I ../../include/ -o flag.o flag.c

flush.o: flush.c
	${CC} ${FLAGS} -c -I ../../include/ -o flush.o flush.c

fpipe.o: fpipe.c
	${CC} ${FLAGS} -c -I ../../include/ -o fpipe.o fpipe.c

niread.o: niread.c
	${CC} ${FLAGS} -c -I ../../include/ -o niread.o niread.c

niwrite.o: niwrite.c
	${CC} ${FLAGS} -c -I ../../include/ -o niwrite.o niwrite.c

nixread.o: nixread.c
	${CC} ${FLAGS} -c -I ../../include/ -o nixread.o nixread.c

nixwrite.o: nixwrite.c
	${CC} ${FLAGS} -c -I ../../include/ -o nixwrite.o nixwrite.c

openfd.o: openfd.c
	${CC} ${FLAGS} -c -I ../../include/ -o openfd.o openfd.c

peekc.o: peekc.c
	${CC} ${FLAGS} -c -I ../../include/ -o peekc.o peekc.c

