all: nls_base.o nls_config.o nls_cp10000.o nls_cp10006.o nls_cp10007.o \
  nls_cp10029.o nls_cp10079.o nls_cp10081.o nls_cp1250.o nls_cp1251.o \
  nls_cp437.o nls_cp737.o nls_cp775.o nls_cp850.o nls_cp852.o nls_cp855.o \
  nls_cp857.o nls_cp860.o nls_cp861.o nls_cp862.o nls_cp863.o nls_cp864.o \
  nls_cp865.o nls_cp866.o nls_cp869.o nls_cp874.o nls_file.o nls_iconv.o \
  nls_iso8859-1.o nls_iso8859-14.o nls_iso8859-15.o nls_iso8859-2.o \
  nls_iso8859-3.o nls_iso8859-4.o nls_iso8859-5.o nls_iso8859-6.o \
  nls_iso8859-7.o nls_iso8859-8.o nls_iso8859-9.o nls_koi8-r.o nls_koi8-u.o

clean:
	rm -f *.o

nls_base.o: nls_base.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_base.o nls_base.c

nls_config.o: nls_config.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_config.o nls_config.c

nls_cp10000.o: nls_cp10000.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp10000.o nls_cp10000.c

nls_cp10006.o: nls_cp10006.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp10006.o nls_cp10006.c

nls_cp10007.o: nls_cp10007.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp10007.o nls_cp10007.c

nls_cp10029.o: nls_cp10029.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp10029.o nls_cp10029.c

nls_cp10079.o: nls_cp10079.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp10079.o nls_cp10079.c

nls_cp10081.o: nls_cp10081.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp10081.o nls_cp10081.c

nls_cp1250.o: nls_cp1250.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp1250.o nls_cp1250.c

nls_cp1251.o: nls_cp1251.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp1251.o nls_cp1251.c

nls_cp437.o: nls_cp437.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp437.o nls_cp437.c

nls_cp737.o: nls_cp737.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp737.o nls_cp737.c

nls_cp775.o: nls_cp775.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp775.o nls_cp775.c

nls_cp850.o: nls_cp850.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp850.o nls_cp850.c

nls_cp852.o: nls_cp852.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp852.o nls_cp852.c

nls_cp855.o: nls_cp855.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp855.o nls_cp855.c

nls_cp857.o: nls_cp857.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp857.o nls_cp857.c

nls_cp860.o: nls_cp860.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp860.o nls_cp860.c

nls_cp861.o: nls_cp861.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp861.o nls_cp861.c

nls_cp862.o: nls_cp862.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp862.o nls_cp862.c

nls_cp863.o: nls_cp863.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp863.o nls_cp863.c

nls_cp864.o: nls_cp864.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp864.o nls_cp864.c

nls_cp865.o: nls_cp865.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp865.o nls_cp865.c

nls_cp866.o: nls_cp866.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp866.o nls_cp866.c

nls_cp869.o: nls_cp869.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp869.o nls_cp869.c

nls_cp874.o: nls_cp874.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_cp874.o nls_cp874.c

nls_file.o: nls_file.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_file.o nls_file.c

nls_iconv.o: nls_iconv.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iconv.o nls_iconv.c

nls_iso8859-1.o: nls_iso8859-1.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-1.o nls_iso8859-1.c

nls_iso8859-14.o: nls_iso8859-14.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-14.o nls_iso8859-14.c

nls_iso8859-15.o: nls_iso8859-15.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-15.o nls_iso8859-15.c

nls_iso8859-2.o: nls_iso8859-2.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-2.o nls_iso8859-2.c

nls_iso8859-3.o: nls_iso8859-3.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-3.o nls_iso8859-3.c

nls_iso8859-4.o: nls_iso8859-4.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-4.o nls_iso8859-4.c

nls_iso8859-5.o: nls_iso8859-5.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-5.o nls_iso8859-5.c

nls_iso8859-6.o: nls_iso8859-6.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-6.o nls_iso8859-6.c

nls_iso8859-7.o: nls_iso8859-7.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-7.o nls_iso8859-7.c

nls_iso8859-8.o: nls_iso8859-8.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-8.o nls_iso8859-8.c

nls_iso8859-9.o: nls_iso8859-9.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_iso8859-9.o nls_iso8859-9.c

nls_koi8-r.o: nls_koi8-r.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_koi8-r.o nls_koi8-r.c

nls_koi8-u.o: nls_koi8-u.c
	${CC} ${FLAGS} -c -I ../include/ -o nls_koi8-u.o nls_koi8-u.c

