# This file was created by Sam Trenholme

all: astoi.o astoll.o astoull.o breakline.o cmpbytes.o comerr.o \
  default.o error.o fexec.o fillbytes.o findbytes.o getargs.o getav0.o \
  getdomainname.o geterrno.o gethostid.o gethostname.o getpagesize.o \
  handlecond.o movebytes.o raisecond.o rename.o saveargs.o seterrno.o \
  snprintf.o spawn.o strcatl.o strdup.o streql.o swabbytes.o usleep.o \

astoi.o: astoi.c
	cc -c -I ../include/ -o astoi.o astoi.c

astoll.o: astoll.c
	cc -c -I ../include/ -o astoll.o astoll.c

astoull.o: astoull.c
	cc -c -I ../include/ -o astoull.o astoull.c

breakline.o: breakline.c
	cc -c -I ../include/ -o breakline.o breakline.c

cmpbytes.o: cmpbytes.c
	cc -c -I ../include/ -o cmpbytes.o cmpbytes.c

comerr.o: comerr.c
	cc -c -I ../include/ -o comerr.o comerr.c

default.o: default.c
	cc -c -I ../include/ -o default.o default.c

error.o: error.c
	cc -c -I ../include/ -o error.o error.c

fexec.o: fexec.c
	cc -c -I ../include/ -o fexec.o fexec.c

fillbytes.o: fillbytes.c
	cc -c -I ../include/ -o fillbytes.o fillbytes.c

findbytes.o: findbytes.c
	cc -c -I ../include/ -o findbytes.o findbytes.c

getargs.o: getargs.c
	cc -c -I ../include/ -o getargs.o getargs.c

getav0.o: getav0.c
	cc -c -I ../include/ -o getav0.o getav0.c

getdomainname.o: getdomainname.c
	cc -c -I ../include/ -o getdomainname.o getdomainname.c

geterrno.o: geterrno.c
	cc -c -I ../include/ -o geterrno.o geterrno.c

gethostid.o: gethostid.c
	cc -c -I ../include/ -o gethostid.o gethostid.c

gethostname.o: gethostname.c
	cc -c -I ../include/ -o gethostname.o gethostname.c

getpagesize.o: getpagesize.c
	cc -c -I ../include/ -o getpagesize.o getpagesize.c

handlecond.o: handlecond.c
	cc -c -I ../include/ -o handlecond.o handlecond.c

movebytes.o: movebytes.c
	cc -c -I ../include/ -o movebytes.o movebytes.c

raisecond.o: raisecond.c
	cc -c -I ../include/ -o raisecond.o raisecond.c

rename.o: rename.c
	cc -c -I ../include/ -o rename.o rename.c

saveargs.o: saveargs.c
	cc -c -I ../include/ -o saveargs.o saveargs.c

seterrno.o: seterrno.c
	cc -c -I ../include/ -o seterrno.o seterrno.c

snprintf.o: snprintf.c
	cc -c -I ../include/ -o snprintf.o snprintf.c

spawn.o: spawn.c
	cc -c -I ../include/ -o spawn.o spawn.c

strcatl.o: strcatl.c
	cc -c -I ../include/ -o strcatl.o strcatl.c

strdup.o: strdup.c
	cc -c -I ../include/ -o strdup.o strdup.c

streql.o: streql.c
	cc -c -I ../include/ -o streql.o streql.c

swabbytes.o: swabbytes.c
	cc -c -I ../include/ -o swabbytes.o swabbytes.c

usleep.o: usleep.c
	cc -c -I ../include/ -o usleep.o usleep.c

